trigger:
- master

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: npm build
      displayName: Gatsby build
- stage: Deploy
  jobs:
  - deployment: DeploySite
    pool:
      vmImage: 'ubuntu-latest'
    environment: CI
    strategy:
      runOnce:
        deploy:
          steps:
            - script: "echo \"todo: deploy\""
