trigger:
- master

stages:
  - stage: Build
    jobs:
      - job: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: npm install
            displayName: Install packages
          - script: echo 'GITHUB_API_TOKEN="$(GitHub-API-Token)"' >> .env.production
            displayName: Create environment file
          - script: npm run build
            displayName: Run Gatsby build
          - task: CopyFiles@2
            displayName: Copy build to staging directory
            inputs:
              Contents: |
                public/**
              TargetFolder: $(Build.ArtifactStagingDirectory)
              CleanTargetFolder: true
          - task: PublishBuildArtifacts@1
            displayName: Publish build artifact
            inputs:
              ArtifactName: chimerical-site
  - stage: Deploy
    jobs:
      - deployment: DeploySite
        pool:
          vmImage: ubuntu-latest
        environment: CI
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadBuildArtifacts@0
                  displayName: Download build artifact
                  inputs:
                    artifactName: chimerical-site
                    buildType: current
                    downloadType: single
                    downloadPath: $(Build.ArtifactStagingDirectory)
                - task: SSH@0
                  displayName: Delete old site
                  inputs:
                    sshEndpoint: Chimerical
                    runOptions: commands
                    commands: rm -rf $(CI)/chimerical-site
                - task: CopyFilesOverSSH@0
                  displayName: Deploy new site
                  inputs:
                    sshEndpoint: Chimerical
                    sourceFolder: $(Build.ArtifactStagingDirectory)/chimerical-site
                    contents: '**'
                    targetFolder: $(CI)
